data:
  build: container/data

db:
  image: mysql
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: nanakenashi
    MYSQL_PASSWORD: nanakenashi
    MYSQL_DATABASE: book_search
  ports:
    - '3306:3306'
  volumes_from:
    - data

web:
  build: container/web
  ports:
    - '5000:5000'
  links:
    - db
